[package]
name = "project-root"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"

[profile.release]
panic = "abort"
lto = true

